import type { DesignTheme } from "../types";

export const DEFAULT_PRESET: DesignTheme = {
  id: "default",
  name: "Manrope System",
  emoji: "🎨",
  fontFamily: "Manrope",
  primitives: {
    grey: {
      100: "#f4f4f2",
      200: "#eae9e5",
      300: "#dfddd8",
      400: "#cac7be",
      500: "#a29f98",
      600: "#797772",
      700: "#51504c",
      800: "#282826",
      900: "#0a0a0a",
    },
    primary: {
      100: "#fff3cd",
      200: "#ffe79b",
      300: "#ffdc68",
      400: "#ffd036",
      500: "#ffc404",
      600: "#cc9d03",
      700: "#997602",
      800: "#664e02",
      900: "#332701",
    },
    secondary: {
      100: "#fddfcf",
      200: "#fbbf9e",
      300: "#f99e6e",
      400: "#f77e3d",
      500: "#f55e0d",
      600: "#c44b0a",
      700: "#933808",
      800: "#622605",
      900: "#311303",
    },
    pink: {
      100: "#efe1ee",
      200: "#dfc3dc",
      300: "#d0a4cb",
      400: "#c086b9",
      500: "#b068a8",
      600: "#8d5386",
      700: "#6a3e65",
      800: "#462a43",
      900: "#231522",
    },
  },
  semantics: [
    { name: "background-neutral-primary", value: "grey.100", type: "color" },
    { name: "background-neutral-secondary", value: "grey.200", type: "color" },
    { name: "background-neutral-tertiary", value: "grey.300", type: "color" },
    { name: "background-neutral-disable", value: "grey.400", type: "color" },
    {
      name: "background-neutral-inverse-primary",
      value: "grey.900",
      type: "color",
    },
    {
      name: "background-neutral-inverse-secondary",
      value: "grey.800",
      type: "color",
    },
    {
      name: "background-neutral-inverse-tertiary",
      value: "grey.700",
      type: "color",
    },
    { name: "background-brand-primary-50", value: "#ffc40466", type: "color" },
    { name: "background-brand-secondary", value: "primary.400", type: "color" },
    { name: "background-brand-tertiary", value: "primary.300", type: "color" },
    { name: "background-brand-primary", value: "primary.500", type: "color" },
    { name: "text-neutral-primary", value: "grey.900", type: "color" },
    { name: "text-neutral-secondary", value: "grey.800", type: "color" },
    { name: "text-neutral-tertiary", value: "grey.700", type: "color" },
    { name: "text-neutral-disabled", value: "grey.600", type: "color" },
    { name: "text-inverse-primary", value: "grey.100", type: "color" },
    { name: "text-inverse-secondary", value: "grey.200", type: "color" },
    { name: "text-inverse-tertiary", value: "grey.300", type: "color" },
    { name: "text-brand-primary", value: "primary.900", type: "color" },
    { name: "border-neutral-primary", value: "grey.300", type: "color" },
    { name: "border-neutral-secondary", value: "grey.400", type: "color" },
    { name: "border-neutral-active", value: "primary.500", type: "color" },
    { name: "border-neutral-focus", value: "grey.900", type: "color" },
    { name: "border-inverse-primary", value: "grey.800", type: "color" },
    { name: "border-inverse-secondary", value: "grey.700", type: "color" },
    { name: "border-inverse-active", value: "primary.600", type: "color" },
    { name: "border-inverse-focus", value: "grey.100", type: "color" },
    { name: "border-brand-primary", value: "primary.900", type: "color" },
    { name: "border-brand-secondary", value: "primary.200", type: "color" },
    { name: "border-brand-active", value: "primary.800", type: "color" },
    { name: "border-brand-focus", value: "grey.900", type: "color" },
  ],
  typography: {
    caption: {
      size: "0.813rem",
      lineHeight: "138%",
      letterSpacing: "0",
      weight: 400,
    },
    paragrafo: {
      size: "1rem",
      lineHeight: "138%",
      letterSpacing: "0",
      weight: 400,
    },
    "paragrafo-l": {
      size: "1.25rem",
      lineHeight: "138%",
      letterSpacing: "0",
      weight: 400,
    },
    h5: {
      size: "1.25rem",
      lineHeight: "120%",
      letterSpacing: "0",
      weight: 500,
    },
    h4: {
      size: "1.563rem",
      lineHeight: "120%",
      letterSpacing: "0",
      weight: 500,
    },
    h3: {
      size: "1.938rem",
      lineHeight: "120%",
      letterSpacing: "0",
      weight: 500,
    },
    h2: {
      size: "2.438rem",
      lineHeight: "120%",
      letterSpacing: "0",
      weight: 500,
    },
    h1: {
      size: "3.063rem",
      lineHeight: "120%",
      letterSpacing: "0",
      weight: 500,
    },
  },
  breakpoints: { sm: "27.5rem", md: "46.5rem", lg: "90rem" },
};

export const DARK_PRESET: DesignTheme = {
  id: "dark",
  name: "Midnight Neon",
  emoji: "🌌",
  fontFamily: "JetBrains Mono",
  primitives: {
    grey: {
      100: "#e2e8f0",
      200: "#cbd5e1",
      300: "#94a3b8",
      400: "#64748b",
      500: "#475569",
      600: "#334155",
      700: "#1e293b",
      800: "#0f172a",
      900: "#020617",
    },
    primary: {
      100: "#e0e7ff",
      200: "#c7d2fe",
      300: "#a5b4fc",
      400: "#818cf8",
      500: "#6366f1",
      600: "#4f46e5",
      700: "#4338ca",
      800: "#3730a3",
      900: "#312e81",
    },
    secondary: {
      100: "#fce7f3",
      200: "#fbcfe8",
      300: "#f9a8d4",
      400: "#f472b6",
      500: "#ec4899",
      600: "#db2777",
      700: "#be185d",
      800: "#9d174d",
      900: "#831843",
    },
    pink: {
      100: "#fae8ff",
      200: "#f0abfc",
      300: "#e879f9",
      400: "#d946ef",
      500: "#c026d3",
      600: "#a21caf",
      700: "#86198f",
      800: "#701a75",
      900: "#4a044e",
    },
  },
  semantics: [
    { name: "background-neutral-primary", value: "grey.900", type: "color" },
    { name: "background-neutral-secondary", value: "grey.800", type: "color" },
    { name: "background-neutral-tertiary", value: "grey.700", type: "color" },
    { name: "background-neutral-disable", value: "grey.600", type: "color" },
    {
      name: "background-neutral-inverse-primary",
      value: "grey.100",
      type: "color",
    },
    {
      name: "background-neutral-inverse-secondary",
      value: "grey.200",
      type: "color",
    },
    {
      name: "background-neutral-inverse-tertiary",
      value: "grey.300",
      type: "color",
    },
    { name: "background-brand-primary-50", value: "#6366f166", type: "color" },
    { name: "background-brand-secondary", value: "primary.400", type: "color" },
    { name: "background-brand-tertiary", value: "primary.300", type: "color" },
    { name: "background-brand-primary", value: "primary.500", type: "color" },
    { name: "text-neutral-primary", value: "grey.100", type: "color" },
    { name: "text-neutral-secondary", value: "grey.200", type: "color" },
    { name: "text-neutral-tertiary", value: "grey.300", type: "color" },
    { name: "text-neutral-disabled", value: "grey.500", type: "color" },
    { name: "text-inverse-primary", value: "grey.900", type: "color" },
    { name: "text-inverse-secondary", value: "grey.800", type: "color" },
    { name: "text-inverse-tertiary", value: "grey.700", type: "color" },
    { name: "text-brand-primary", value: "primary.300", type: "color" },
    { name: "border-neutral-primary", value: "grey.700", type: "color" },
    { name: "border-neutral-secondary", value: "grey.600", type: "color" },
    { name: "border-neutral-active", value: "primary.500", type: "color" },
    { name: "border-neutral-focus", value: "grey.100", type: "color" },
    { name: "border-inverse-primary", value: "grey.200", type: "color" },
    { name: "border-inverse-secondary", value: "grey.300", type: "color" },
    { name: "border-inverse-active", value: "primary.400", type: "color" },
    { name: "border-inverse-focus", value: "grey.900", type: "color" },
    { name: "border-brand-primary", value: "primary.500", type: "color" },
    { name: "border-brand-secondary", value: "primary.700", type: "color" },
    { name: "border-brand-active", value: "primary.300", type: "color" },
    { name: "border-brand-focus", value: "grey.100", type: "color" },
  ],
  typography: {
    caption: {
      size: "0.75rem",
      lineHeight: "140%",
      letterSpacing: "0.02em",
      weight: 400,
    },
    paragrafo: {
      size: "0.875rem",
      lineHeight: "150%",
      letterSpacing: "0",
      weight: 400,
    },
    "paragrafo-l": {
      size: "1rem",
      lineHeight: "150%",
      letterSpacing: "0",
      weight: 400,
    },
    h5: {
      size: "1.125rem",
      lineHeight: "130%",
      letterSpacing: "-0.01em",
      weight: 600,
    },
    h4: {
      size: "1.25rem",
      lineHeight: "130%",
      letterSpacing: "-0.01em",
      weight: 600,
    },
    h3: {
      size: "1.5rem",
      lineHeight: "120%",
      letterSpacing: "-0.02em",
      weight: 600,
    },
    h2: {
      size: "2rem",
      lineHeight: "120%",
      letterSpacing: "-0.02em",
      weight: 700,
    },
    h1: {
      size: "2.5rem",
      lineHeight: "110%",
      letterSpacing: "-0.03em",
      weight: 800,
    },
  },
  breakpoints: { sm: "27.5rem", md: "46.5rem", lg: "90rem" },
};

export const BLANK_CANVAS_THEME: DesignTheme = {
  id: "custom",
  name: "Custom System",
  emoji: "🎨",
  fontFamily: "Inter",
  primitives: {
    grey: {
      100: "#fafafa",
      200: "#f4f4f5",
      300: "#e4e4e7",
      400: "#d4d4d8",
      500: "#a1a1aa",
      600: "#71717a",
      700: "#52525b",
      800: "#27272a",
      900: "#18181b",
    },
    primary: {
      100: "#ede9fe",
      200: "#ddd6fe",
      300: "#c4b5fd",
      400: "#a78bfa",
      500: "#8b5cf6",
      600: "#7c3aed",
      700: "#6d28d9",
      800: "#5b21b6",
      900: "#4c1d95",
    },
  },
  semantics: [
    {
      name: "background-neutral-primary",
      value: "grey.100",
      type: "color",
    },
    {
      name: "text-neutral-primary",
      value: "grey.900",
      type: "color",
    },
    {
      name: "border-neutral-primary",
      value: "grey.300",
      type: "color",
    },
  ],
  typography: {
    caption: {
      size: "0.75rem",
      lineHeight: "140%",
      letterSpacing: "0",
      weight: 400,
    },
    paragrafo: {
      size: "1rem",
      lineHeight: "150%",
      letterSpacing: "0",
      weight: 400,
    },
    h1: {
      size: "2.25rem",
      lineHeight: "120%",
      letterSpacing: "-0.02em",
      weight: 700,
    },
  },
  breakpoints: { sm: "640px", md: "768px", lg: "1024px" },
};

export const PRESETS: readonly DesignTheme[] = [DEFAULT_PRESET, DARK_PRESET];